/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The image resource details
 */
export class BrowseMenuItemImages extends SpeakeasyBase {
  /**
   * The virtual id for the image resource
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * Information about the image
   */
  @SpeakeasyMetadata()
  @Expose({ name: "meta" })
  meta?: string;

  /**
   * The order in which the image was added/appears
   */
  @SpeakeasyMetadata()
  @Expose({ name: "order" })
  order?: number;

  /**
   * The url to the image resource
   */
  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url?: string;
}

/**
 * Additional data associated with the menu item
 */
export class BrowseMenuItemParams extends SpeakeasyBase {
  /**
   * The virtual id for the parameter
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * A description for the parameter
   */
  @SpeakeasyMetadata()
  @Expose({ name: "kind" })
  kind?: string;

  /**
   * The value for the parameter
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value?: string;
}

/**
 * The browse menu item object
 */
export class BrowseMenuItem extends SpeakeasyBase {
  /**
   * The browse menu item object
   */
  @SpeakeasyMetadata()
  @Expose({ name: "children" })
  @Type(() => BrowseMenuItem)
  children?: BrowseMenuItem;

  /**
   * A list of image resources
   */
  @SpeakeasyMetadata({ elemType: BrowseMenuItemImages })
  @Expose({ name: "images" })
  @Type(() => BrowseMenuItemImages)
  images?: BrowseMenuItemImages[];

  /**
   * The menu item name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The database id for the menu item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: string;

  /**
   * The position the menu item appears in the UI
   */
  @SpeakeasyMetadata()
  @Expose({ name: "order" })
  order?: number;

  /**
   * List of additional data associated with the menu item
   */
  @SpeakeasyMetadata({ elemType: BrowseMenuItemParams })
  @Expose({ name: "params" })
  @Type(() => BrowseMenuItemParams)
  params?: BrowseMenuItemParams[];

  /**
   * The database id for the menu item parent
   */
  @SpeakeasyMetadata()
  @Expose({ name: "parentId" })
  parentId?: string;

  /**
   * The relative menu item url path
   */
  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url?: string;
}
