/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The server error response object
 */
export class ErrorT extends SpeakeasyBase {
  /**
   * The code associated with the type of server error
   */
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code: string;

  /**
   * The message associated with the server error
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;
}
