/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * The `x-site-context` header is a JSON object that must contain your account ID. This header can also be called `X-Site-Context` based on your stylistic preferences.
 */
export class XSiteContext extends SpeakeasyBase {
  /**
   * The 24 character client's co-pilot account identifier
   */
  @SpeakeasyMetadata({ data: "header, name=account" })
  account: string;
}
