/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Transform, Type } from "class-transformer";

export class GetLivePageV2Request extends SpeakeasyBase {
  /**
   * A comma-separated list of channel ids
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=channels",
  })
  channels?: string;

  /**
   * The relative page url for which to retrieve the live page version
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=url" })
  url: string;

  /**
   * The `x-site-context` header is a JSON object that must contain your account ID. This header can also be called `X-Site-Context` based on your stylistic preferences.
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=x-site-context",
  })
  xSiteContext?: shared.XSiteContext;
}

/**
 * 204 response object
 */
export class GetLivePageV2204ApplicationJSON extends SpeakeasyBase {
  /**
   * Message describing the result of the response
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * Message describing the request
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status?: string;

  /**
   * The response status code
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status_code" })
  statusCode?: number;
}

/**
 * The page type object
 */
export class GetLivePageV2200ApplicationJSONDataPagePageType extends SpeakeasyBase {
  /**
   * True if page type is marked is default; false otherwise
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isDefault" })
  isDefault?: boolean;

  /**
   * The page type Name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The URL prefix associated with the page type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "urlPrefix" })
  urlPrefix?: string;
}

/**
 * The metadata associated with the SEO field
 */
export class GetLivePageV2200ApplicationJSONDataPageSeoFieldsMetadata extends SpeakeasyBase {
  /**
   * The virutal id associated with the SEO field metadata
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * Metadata content
   */
  @SpeakeasyMetadata()
  @Expose({ name: "content" })
  content?: string;

  /**
   * The date and time the metadata was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt?: Date;

  /**
   * Metadata name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The date and time the metadata was last updated
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updatedAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt?: Date;
}

/**
 * The SEO fields
 */
export class GetLivePageV2200ApplicationJSONDataPageSeoFields extends SpeakeasyBase {
  /**
   * The virtual id associated with the SEO field
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * The date and time the SEO field was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt?: Date;

  /**
   * SEO field description
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * The list of metadata associated with the SEO field
   */
  @SpeakeasyMetadata({
    elemType: GetLivePageV2200ApplicationJSONDataPageSeoFieldsMetadata,
  })
  @Expose({ name: "metadata" })
  @Type(() => GetLivePageV2200ApplicationJSONDataPageSeoFieldsMetadata)
  metadata?: GetLivePageV2200ApplicationJSONDataPageSeoFieldsMetadata[];

  /**
   * SEO field title
   */
  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title?: string;

  /**
   * The date and time the SEO field was last updated
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updatedAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt?: Date;
}

/**
 * The page object
 */
export class GetLivePageV2200ApplicationJSONDataPage extends SpeakeasyBase {
  /**
   * The versionKey associated with the page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "__v" })
  v?: number;

  /**
   * The database id associated with the page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * A deprecated field holding channel information
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channel" })
  channel?: number[];

  /**
   * The channel ids associated with the page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channels" })
  channels?: string[];

  /**
   * The date and time the page was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt?: Date;

  /**
   * True if the page is active; false otherwise
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isActive" })
  isActive?: boolean;

  /**
   * True if the page is archived; false otherwise
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isArchived" })
  isArchived?: boolean;

  /**
   * The page name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * An identifier used for the page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageId" })
  pageId?: number;

  /**
   * The page type object
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageType" })
  @Type(() => GetLivePageV2200ApplicationJSONDataPagePageType)
  pageType?: GetLivePageV2200ApplicationJSONDataPagePageType;

  /**
   * The relative page url
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageUrl" })
  pageUrl?: string;

  /**
   * The SEO fields
   */
  @SpeakeasyMetadata()
  @Expose({ name: "seoFields" })
  @Type(() => GetLivePageV2200ApplicationJSONDataPageSeoFields)
  seoFields?: GetLivePageV2200ApplicationJSONDataPageSeoFields;

  /**
   * Name of the page type of page (optional)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "typeName" })
  typeName?: string;

  /**
   * URL of the page type of page (optional)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "typeUrl" })
  typeUrl?: string;

  /**
   * The date and time the page was updated
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updatedAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt?: Date;
}

/**
 * The version object
 */
export class GetLivePageV2200ApplicationJSONDataVersion extends SpeakeasyBase {
  /**
   * The versionKey associated with the version
   */
  @SpeakeasyMetadata()
  @Expose({ name: "__v" })
  v?: number;

  /**
   * The database id associated with the version
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * A deprecated field holding channel information
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channel" })
  channel?: number[];

  /**
   * The channel ids associated with the version
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channels" })
  channels?: string[];

  /**
   * The list of components
   */
  @SpeakeasyMetadata()
  @Expose({ name: "components" })
  components?: Record<string, any>[];

  /**
   * The date and time the version was created
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt?: Date;

  /**
   * The description associated with the version
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * The date when the version will no longer be live
   */
  @SpeakeasyMetadata()
  @Expose({ name: "endDate" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  endDate?: Date;

  /**
   * True if the version is archived; false otherwise
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isArchived" })
  isArchived?: boolean;

  /**
   * The version name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The database id of the page associated with the version
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageId" })
  pageId?: string;

  /**
   * The date and time the version was published
   */
  @SpeakeasyMetadata()
  @Expose({ name: "startDate" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  startDate?: Date;

  /**
   * The current status of the version
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status?: string;

  /**
   * The date and time the version was last updated
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updatedAt" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt?: Date;

  /**
   * An identifier used for the version
   */
  @SpeakeasyMetadata()
  @Expose({ name: "versionId" })
  versionId?: number;
}

/**
 * The data object holding the live page and version details
 */
export class GetLivePageV2200ApplicationJSONData extends SpeakeasyBase {
  /**
   * The page details
   */
  @SpeakeasyMetadata()
  @Expose({ name: "page" })
  @Type(() => GetLivePageV2200ApplicationJSONDataPage)
  page?: GetLivePageV2200ApplicationJSONDataPage;

  /**
   * An array holding the live page version
   */
  @SpeakeasyMetadata({ elemType: GetLivePageV2200ApplicationJSONDataVersion })
  @Expose({ name: "version" })
  @Type(() => GetLivePageV2200ApplicationJSONDataVersion)
  version?: GetLivePageV2200ApplicationJSONDataVersion[];
}

/**
 * 200 response object
 */
export class GetLivePageV2200ApplicationJSON extends SpeakeasyBase {
  /**
   * The data object holding the live page and version details
   */
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  @Type(() => GetLivePageV2200ApplicationJSONData)
  data?: GetLivePageV2200ApplicationJSONData;

  /**
   * Status message
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * The response status code
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status_code" })
  statusCode?: number;
}

export class GetLivePageV2Response extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Page url not specified
   */
  @SpeakeasyMetadata()
  error?: shared.ErrorT;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Successful operation
   */
  @SpeakeasyMetadata()
  getLivePageV2200ApplicationJSONObject?: GetLivePageV2200ApplicationJSON;

  /**
   * Page is not live or is inactive
   */
  @SpeakeasyMetadata()
  getLivePageV2204ApplicationJSONObject?: GetLivePageV2204ApplicationJSON;
}
