/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetLiveMenuV2QueryParams extends SpeakeasyBase {
  /**
   * A comma-separated list of channel ids
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=channels",
  })
  channels?: string;

  /**
   * The depth to traverse when returning menu items
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=depth" })
  depth?: number;

  /**
   * The id for a specific menu item, associated with a live menu, to retrieve
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=nodeId",
  })
  nodeId?: string;

  /**
   * The id for a parent menu item, associated with a live menu, for which to retrieve the sub-menu items for
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=parentId",
  })
  parentId?: string;
}

export class GetLiveMenuV2Headers extends SpeakeasyBase {
  /**
   * The `x-site-context` header is a JSON object that must contain your account ID. This header can also be called `X-Site-Context` based on your stylistic preferences.
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=x-site-context",
  })
  xSiteContext?: shared.XSiteContext;
}

export class GetLiveMenuV2Request extends SpeakeasyBase {
  @SpeakeasyMetadata()
  queryParams: GetLiveMenuV2QueryParams;

  @SpeakeasyMetadata()
  headers: GetLiveMenuV2Headers;
}

/**
 * The menu and its menu item details
 */
export class GetLiveMenuV2200ApplicationJSONMenu1 extends SpeakeasyBase {
  /**
   * The channel ids associated with the menu
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channels" })
  channels?: string[];

  /**
   * The browse menu item object
   */
  @SpeakeasyMetadata()
  @Expose({ name: "children" })
  @Type(() => shared.BrowseMenuItem)
  children?: shared.BrowseMenuItem;

  /**
   * The database id for menu
   */
  @SpeakeasyMetadata()
  @Expose({ name: "menuId" })
  menuId?: string;

  /**
   * The menu name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * An object describing the request query
 */
export class GetLiveMenuV2200ApplicationJSONQuery extends SpeakeasyBase {
  /**
   * The channel id specified in the request
   */
  @SpeakeasyMetadata()
  @Expose({ name: "channelId" })
  channelId?: string;

  /**
   * The search depth specified in the request
   */
  @SpeakeasyMetadata()
  @Expose({ name: "depth" })
  depth?: number;

  /**
   * The node id specified in the request
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: string;

  /**
   * The menu parent id specified in the request
   */
  @SpeakeasyMetadata()
  @Expose({ name: "parentId" })
  parentId?: string;
}

/**
 * 200 response object
 */
export class GetLiveMenuV2200ApplicationJSON extends SpeakeasyBase {
  /**
   * The menu details or a list of its menu item details
   */
  @SpeakeasyMetadata()
  @Expose({ name: "menu" })
  menu?: any[];

  /**
   * An object describing the request query
   */
  @SpeakeasyMetadata()
  @Expose({ name: "query" })
  @Type(() => GetLiveMenuV2200ApplicationJSONQuery)
  query?: GetLiveMenuV2200ApplicationJSONQuery;
}

export class GetLiveMenuV2Response extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Menu not found
   */
  @SpeakeasyMetadata()
  error?: shared.ErrorT;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Successful operation
   */
  @SpeakeasyMetadata()
  getLiveMenuV2200ApplicationJSONObject?: GetLiveMenuV2200ApplicationJSON;
}
