name: Generate
"on":
  workflow_dispatch:
    inputs:
      force:
        description: ""
        type: ""
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v7
    with:
      languages: |
        - typescript
      mode: pr
      openapi_doc_location: ./fabric.json
      publish_typescript: true
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
